name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Extract Project
        run: |
          unzip -o FinalApp.zip
          ls -la
          ls -la FinalApp

      - name: Make Gradlew Executable
        working-directory: FinalApp
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: FinalApp
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aryan-app-APK
          path: FinalApp/app/build/outputs/apk/debug/app-debug.apk
